adventuregamestudio/ags-manual

make-chm-from-htmlhelp.sh
- Suggested fix for #14 is to enable binary TOC and index (but unfortunately when I've tested this I've not noticed a difference)
- Build on other platforms if you have chmcmd from somewhere else and don't have bash
- Don't validate with a checksum from the same source as the download
- Exit on checksum mismatch
- Build in a subshell so the current directory doesn't get modified
=> Enable binary toc and index, and build on other platforms

_static/custom.css, _templates/layout.html, conf.py
For a better render for pages in the CHM file, and fitting more text on the screen in general, the changes are:
- removal of the top margin from the document wrapper
- the removal of the footer, for the htmlhelp builder
- use of a smaller font size, everywhere
=> Render with less whitespace and more text

.travis.yml
This should allow building without script blocks requiring root permissions (if container infrastructure becomes available again, this would let it run on that, I think).
This is a second attempt, as my previous try didn't have an access token.
=> Don't use sudo on TravisCI

.travis.yml, Makefile
- Don't recursively clean on Windows
This was left over from an early version of the Makefile, with recursive use of Make
- Don't hard-code Makefile name
This was previously in, but was removed when I was accidentally using an older version of Make
- Print warning when not on Windows and HHC is defined
HHC return codes need to be inverted, so the shell command that does this is not portable (you can't just use chmcmd here)
- Use subshell to avoid directory change and get a wildcard match
Script block issue in Travis-CI seems to be that shell globbing doesn't function in the actual block
~~**my final attempt before I never touch this again**~~
**seems to have worked**
=> miscellaneous fixes / improvements

.travis.yml, appveyor.yml
If not using the latest version of Pandoc there is no requirement to use query the latest download URL - this should fix the issue of PRs potentially failing if API access to Github is throttled. This also opens the possibility to run multiple jobs using different versions of Pandoc.
=> Use fixed Pandoc version

CONTRIBUTING.md, lua/agsman.lua, lua/rewrite_links.lua, lua/set_title.lua, lua/write_genindex.lua, lua/write_hhc.lua, lua/write_hhk.lua, lua/write_hhp.lua, lua/write_metablock.lua, lua/write_metajs.lua
* Adds CONTRIBUTING.md which someone who wants to modify or replace the build system would need to read (I've left a space at the top for guidelines on editing the wiki pages themselves).
* Slightly improves comments at the start of each Lua file
Internally the Lua files are not very commented, but I'm not sure at the moment whether to try abd document these functions or just provide links to Pandoc documentation - the majority of functions only make sense within the context of Pandoc.
=> Add some documentation for the build process

lua/agsman.lua, lua/write_metablock.lua
~~Existing Screen functions were mistakenly indexed as Screen.Function, so index names were not valid.~~
* Cross referencing the autocomplete file with the index revealed a few places where the script functions needed to be forced as global
* Also adds override ability for where the page structures do not directly relate to scripting objects
* Fixes remaining indices for 'Multimedia' functions
=> More fixes for the namespaces of indices

Makefile
Switches to wildcard copying for css and static, and just specifies the source as a pre-requisite for stp copy. @ericoporto this should fix the issue you had when testing changes in #63.
=> Fix static copy operations where source was modified

.travis.yml, appveyor.yml
Mostly Travis-CI changes, but also modifying the Appveyor configuration to stay in sync with it.
- Get environment variables that shouldn't be modified by the build environment out of the build matrix
- Detect macOS (or changes in program availability) and adjust scripted actions to suit
- Remove URL checks (left over from when the download URL was acquired through an API lookup)
=> Clean-up CI builds and enable macOS

GNUmakefile, html/css/main.css, lua/insert_anchors.lua
This lets you manually obtain a header's anchor link if someone needs to know the link to a specific part of the page. This doesn't increase the number of visible elements (so doesn't make the page any more cluttered) and keeps the automatic TOC looking correct.
Part of #55
=> Add anchor links to content headers

.travis.yml
...so that querying the current release doesn't need to use the GitHub API
This means CI actions that don't have a GitHub token can reliably query the current release (as long as GitHub Pages is working).
=> Write tag to a file in the HTML build

.travis.yml, README.md, appveyor.yml, lua/write_genindex.lua, lua/write_hhk.lua, lua/write_metablock.lua, lua/write_metacheck.lua, lua/write_metajs.lua
This modifies the page metadata to record whether an item relates to the script API or not. When pages are rendered the CHM index will create non-script items as a child list of the page title (so order is dictacted by the page title). When pages are rendered for the website non-script items have their page title appended (and so remain alphabetical).
This is primarily for #98 since index entries for regular pages would stop the script editor being able to directly open the pages (due to matching multiple items). For the moment, since the script editor assumes that every item it needs is at the top level of the index, shifting the majority of non-script items out of this top level list seems the best way to keep it operational.
=> Identify index item type in metadata

GNUmakefile
- removing extra closing parenthesis from GNUmakefile 
- some order functions in lua files I think are supposed to be local and not global, so I switched to local
=> Minor fixes

CONTRIBUTING.md, GNUmakefile, README.md, lua/agsman.lua, lua/write_genindex.lua, lua/write_hhk.lua, lua/write_metablock.lua, lua/write_metacheck.lua, lua/write_metajs.lua
The main purposes of switching:
- The home-made YAML encoder wasn't complete enough to safely escape content
- The loading of concatenated YAML metablocks was incredible slow
- The Lua serialization is simpler, safer, faster, and doesn't require the use of functions like stringify to retrieve strings from Pandoc's internal metadata representation of a YAML metablock (which seems to modify string content in some cases)
- The Lua serialization function returns a string which is indented and sorted, so it also works for debug purposes when you just want to dump a table
Additional changes:
- Testing revealed that some of the data wasn't being sorted and that the utility module and sorting functions were broken in their scoping, so these have also been fixed
- To allow testing by diffing build …
=> Switch metadata from YAML to Lua table serialization

.github/workflows/job.m4, .github/workflows/release.m4, .github/workflows/release.yml, .github/workflows/test.m4, .github/workflows/test.yml, GNUmakefile, README.md, lua/insert_toc.lua
TOC will possibly be inserted above or below the first page heading depending on:
- whether a later heading has the same level as the first
- the total number of headings
TOC depth is loosely tracked against the actual heading depth, which should look reasonable where heading levels do not attempt a negative shift (if the page structure looks OK then likely the TOC will look OK too).
Raises minimum Pandoc version required to 2.9.2 since this is where pandoc.List gained the insert method.
Fixes #119
=> Add Lua filter for dynamic TOC insert in htmlhelp pages

.github/workflows/release.m4, .github/workflows/release.yml
- allows creating release from GH interface
- action from url: https://github.com/ncipollo/release-action
Here's an example released created using the web interface: https://github.com/ericoporto/ags-manual/releases/tag/v0.6.3
This uses a community action that seems more maintained than the one in PR #138 , and preserves previous behavior of releasing through web interface (fixes #137).
=> ci: switch from GH release action to community maintained

.gitattributes, GNUmakefile, html/css/main.css, html/js/darkmode.js, html/template.html5
this PR adds a toggle for light and dark mode in the web version of the manual:
http://ericoporto.github.io/ags-manual
If you have loaded it before, use Ctrl+Shift+R or whatever your browser's empty cache and reload shortcut is to remove previous builds of it from your cache.
fixes over PR #140 
Edit: updated the build in my branch too.
=> adds toggable dark/light mode

html/css/main.css, html/template.html5, html/template.js
- word match toggle
- highlight toggle
- toggle state persistence
- theme improvements
- better icons
- revamped search box
- got to first highlighted match when jumping from search (if enabled)
It would be nice if we had the _Sidebar.md content in the sidebar, and the current page stuff appears in a separate box. I could make it work like other doc sites, where the "current page" box can move on the right, or the upper part of the sidebar depending how much space is available.
Having the main TOC always visible would also help reduce the amount of clicks to get back to the index page.
=> Quality of life improvements

html/css/main.css, html/template.js
Applies extra styling to the INFO/IMPORTANT/TIP paragraph blocks (but not the old ones with the image icon).
The substitution happens at runtime via javascript.
I made NOTE violet because blue is too soothing and safe, users might gloss over it.
=> Programmatic styling of INFO/IMPORTANT/TIP

meta/approved_links.txt
ffmpeg2theora website is no longer available and ffmpeg makes a really good job converting to the format. I updated the PlayVideo doc to recommend ffmpeg and I'm updating the approved links here.
https://github.com/adventuregamestudio/ags-manual/wiki/Multimedia#playvideo
=> Update ffmpeg links approved_links.txt

.gitmodules, CONTRIBUTING.md, Makefile.am, README.md, html/css/main.css, html/template.html5
Preliminary step to #242: 
- Linking to another repo instead of the wiki.
- Added an edit link to github above the footer.
Notes:
- links from github preview don't work because it expects a .md extension
- since the source is still pulled through a submodule, we still have the same pro/con as before that it checks out the same submodule version which was committed
=> Pull md files from doc source repo instead of wiki
